/**
 * Comprehensive English-to-Bengali translation map for Hadith section/chapter names
 * Used across all 6 major hadith books (Bukhari, Muslim, Abu Dawud, Tirmidhi, Nasai, Ibn Majah)
 */

const SECTION_NAME_MAP: Record<string, string> = {
  // Common across multiple books
  "Revelation": "ওহী (প্রত্যাদেশ)",
  "Belief": "ঈমান",
  "Faith": "ঈমান",
  "Knowledge": "ইলম (জ্ঞান)",
  "Ablutions (Wudu')": "অযু",
  "Ablution (Wudu')": "অযু",
  "Ablutions": "অযু",
  "Purification (Kitab Al-Taharah)": "পবিত্রতা (তাহারাত)",
  "Purification": "পবিত্রতা (তাহারাত)",
  "The Book of Purification": "পবিত্রতা",
  "Bathing (Ghusl)": "গোসল",
  "Menstrual Periods": "হায়েয (ঋতুস্রাব)",
  "Menstruation (Kitab Al-Haid)": "হায়েয (ঋতুস্রাব)",
  "Rubbing hands and feet with dust (Tayammum)": "তায়াম্মুম",
  "Tayammum": "তায়াম্মুম",
  "Prayers (Salat)": "সালাত (নামায)",
  "Prayer": "সালাত (নামায)",
  "Prayer (Kitab Al-Salat)": "সালাত (নামায)",
  "The Book of Prayer": "সালাত (নামায)",
  "The Book of Prayers": "সালাত (নামায)",
  "Prayer (Kitab Al-Salat): Details of Commencing Prayer": "নামাযের বিস্তারিত বিবরণ",
  "Times of the Prayers": "সালাতের ওয়াক্তসমূহ",
  "Prayer (Kitab Al-Salat): Prayer at Night": "রাতের নামায",
  "Call to Prayers (Adhaan)": "আযান",
  "The Adhan (Call to Prayer)": "আযান",
  "Adhan": "আযান",
  "Friday Prayer": "জুমু'আর সালাত",
  "The Book of Friday (Salat Al-Jumuah)": "জুমু'আর সালাত",
  "Al-Jumu'ah (Friday)": "জুমু'আ",
  "Fear Prayer": "ভয়ের সালাত (সালাতুল খাওফ)",
  "Prayer (Kitab Al-Salat): Prayer during Journey": "সফরের নামায",
  "The Two Festivals (Eids)": "দুই ঈদ",
  "The Two Eid Prayers (Eids)": "দুই ঈদ",
  "The Book of the Two Eid Prayers": "দুই ঈদের সালাত",
  "Witr Prayer": "বিতর সালাত",
  "The Book of Witr": "বিতর সালাত",
  "Invoking Allah for Rain (Istisqaa)": "ইসতিসকা (বৃষ্টির দোয়া)",
  "Eclipses": "সূর্যগ্রহণ ও চন্দ্রগ্রহণ",
  "The Book of the Prayer for Rain (Istisqa)": "ইসতিসকা (বৃষ্টির দোয়া)",
  "The Book of Eclipses": "গ্রহণের সালাত",
  "Prostration During Recital of Quran": "সিজদাতুত তিলাওয়াত",
  "Shortening the Prayers (At-Taqseer)": "সালাত কসর",
  "Shortening the Prayers": "সালাত কসর",
  "Prayer at Night (Tahajjud)": "তাহাজ্জুদ",
  "The Book of Prayer (Kitab Al-Salat): Voluntary Prayers": "নফল সালাত",
  "Voluntary Prayers": "নফল সালাত",
  "Actions while Praying": "সালাতে কর্মসমূহ",
  "Funerals (Al-Janaa'iz)": "জানাযা",
  "Funerals": "জানাযা",
  "The Book of Funerals": "জানাযা",
  "Funeral (Kitab Al-Jana'iz)": "জানাযা",
  "Obligatory Charity Tax (Zakat)": "যাকাত",
  "The Book of Zakat": "যাকাত",
  "Zakat (Kitab Al-Zakat)": "যাকাত",
  "Zakat": "যাকাত",
  "Obligatory Charity Tax After Ramadaan (Zakat ul Fitr)": "সাদাকাতুল ফিতর",
  "Hajj (Pilgrimage)": "হজ্জ",
  "The Book of Hajj": "হজ্জ",
  "Hajj": "হজ্জ",
  "Pilgrimage (Kitab Al-Manasik Wa'l-Hajj)": "হজ্জ (মানাসিক)",
  "Minor Pilgrimage (Umra)": "উমরা",
  "Umrah": "উমরা",
  "Pilgrims Prevented from Completing the Pilgrimage": "মুহসার (হজ্জে বাধাপ্রাপ্ত)",
  "Penalty of Hunting while on Pilgrimage": "শিকারের কাফফারা",
  "Merits of Madinah": "মদীনার ফযীলত",
  "Virtues of Madinah": "মদীনার ফযীলত",
  "Fasting": "সিয়াম (রোযা)",
  "The Book of Fasting": "সিয়াম (রোযা)",
  "Fasting (Kitab Al-Siyam)": "সিয়াম (রোযা)",
  "Praying at Night in Ramadaan (Taraweeh)": "তারাবীহ",
  "Retiring to a Mosque for Remembrance of Allah (I'tikaf)": "ই'তিকাফ",
  "I'tikaf": "ই'তিকাফ",
  "Sales and Trade": "ক্রয়-বিক্রয়",
  "Business Transactions": "ব্যবসা-বাণিজ্য",
  "Commercial Transactions (Kitab Al-Buyu)": "ক্রয়-বিক্রয়",
  "The Book of Business Transactions": "ব্যবসায়িক লেনদেন",
  "Sales in which a Price is paid for Goods to be Delivered Later (As-Salam)": "সালাম (অগ্রিম ক্রয়)",
  "Pre-emption": "শুফ'আ (অগ্রক্রয়)",
  "Pre-emption in Dwellings And Property (Kitab Al-Shuf'a)": "শুফ'আ",
  "Hiring": "ইজারা (ভাড়া)",
  "Transferring of a Debt from One Person to Another (Al-Hawaala)": "হাওয়ালা",
  "Representation, Authorization, Business by Proxy": "ওকালাত (প্রতিনিধিত্ব)",
  "Agriculture": "কৃষি",
  "Distribution of Water": "পানি বন্টন",
  "Loans, Payment of Loans, Freezing of Property, Bankruptcy": "ঋণ ও দেউলিয়া",
  "Lost Things Picked up by Someone (Luqaata)": "লুকাতা (হারানো বস্তু)",
  "Oppressions": "মাযালিম (অত্যাচার)",
  "Partnership": "শিরকাত (অংশীদারিত্ব)",
  "Mortgaging": "রাহন (বন্ধক)",
  "Manumission of Slaves": "ইতক (দাস মুক্তি)",
  "Freeing Slaves": "দাস মুক্তি",
  "Gifts": "হিবা (উপহার)",
  "The Book of Gifts": "হিবা (উপহার)",
  "Witnesses": "সাক্ষ্য",
  "Peacemaking": "সুলহ (সন্ধি)",
  "Conditions": "শর্তাবলী",
  "Wills and Testaments (Wasaayaa)": "ওসিয়ত",
  "Wills and Testaments": "ওসিয়ত",
  "Wills (Kitab Al-Wasaya)": "ওসিয়ত",
  "Fighting for the Cause of Allah (Jihaad)": "জিহাদ",
  "Jihad (Kitab Al-Jihad)": "জিহাদ",
  "Jihad": "জিহাদ",
  "The Book of Jihad": "জিহাদ",
  "One-fifth of Booty to the Cause of Allah (Khumus)": "খুমুস (গণীমতের এক-পঞ্চমাংশ)",
  "Beginning of Creation": "সৃষ্টির সূচনা",
  "The Book of the Beginning of Creation": "সৃষ্টির সূচনা",
  "Prophets": "নবী-রাসূলগণ",
  "The Book of Prophets": "নবী-রাসূলগণ",
  "Merits of the Companions of the Prophet ﷺ (Manaqib)": "সাহাবীদের মর্যাদা",
  "Companions of the Prophet": "সাহাবীগণ",
  "Merits of Al-Ansaar": "আনসারদের ফযীলত",
  "The Merits of the Helpers in Madinah (Ansaar)": "আনসারদের ফযীলত",
  "Military Expeditions led by the Prophet ﷺ (Al-Maghaazi)": "মাগাযী (যুদ্ধাভিযান)",
  "Prophetic Commentary on the Quran (Tafseer of the Prophet ﷺ)": "তাফসীর",
  "Virtues of the Quran": "কুরআনের ফযীলত",
  "The Book of Virtues of the Quran": "কুরআনের ফযীলত",
  "Wedlock, Marriage (Nikaah)": "বিবাহ (নিকাহ)",
  "Marriage": "বিবাহ (নিকাহ)",
  "Marriage (Kitab Al-Nikah)": "বিবাহ (নিকাহ)",
  "The Book of Marriage": "বিবাহ (নিকাহ)",
  "Divorce": "তালাক",
  "The Book of Divorce": "তালাক",
  "Divorce (Kitab Al-Talaq)": "তালাক",
  "Supporting the Family": "পরিবারের ভরণপোষণ",
  "Food, Meals": "খাদ্য ও আহার",
  "The Book of Foods": "খাবার",
  "Foods (Kitab Al-At'imah)": "খাদ্য",
  "Sacrifice on Occasion of Birth (`Aqiqa)": "আকীকা",
  "Slaughtering and Hunting": "যবেহ ও শিকার",
  "Al-Adha Festival Sacrifice (Adaahi)": "কুরবানী",
  "The Book of Sacrifices": "কুরবানী",
  "Sacrifice (Kitab Al-Dahaya)": "কুরবানী",
  "Drinks": "পানীয়",
  "The Book of Drinks": "পানীয়",
  "Drinks (Kitab Al-Ashribah)": "পানীয়",
  "Patients": "রোগী",
  "Medicine": "চিকিৎসা",
  "The Book of Medicine": "চিকিৎসা",
  "Medicine (Kitab Al-Tibb)": "চিকিৎসা",
  "Dress": "পোশাক",
  "The Book of Clothes and Adornment": "পোশাক ও সাজসজ্জা",
  "Clothing (Kitab Al-Libas)": "পোশাক",
  "Good Manners and Form (Al-Adab)": "আদব (শিষ্টাচার)",
  "Al-Adab": "আদব (শিষ্টাচার)",
  "Good Manners": "আদব (শিষ্টাচার)",
  "Asking Permission": "অনুমতি চাওয়া",
  "Invocations": "দোয়া ও যিকির",
  "Supplications": "দোয়া",
  "The Book of Supplications": "দোয়া",
  "Supplication (Kitab Al-Da'awat)": "দোয়া",
  "To make the Heart Tender (Ar-Riqaq)": "রিকাক (হৃদয় নরমকারী)",
  "Ar-Riqaq": "রিকাক",
  "Heart Softeners": "রিকাক (হৃদয় নরমকারী)",
  "Divine Will (Al-Qadar)": "তাকদীর",
  "Destiny (Kitab-ul-Qadr)": "তাকদীর",
  "The Book of Destiny": "তাকদীর",
  "Oaths and Vows": "শপথ ও মানত",
  "The Book of Oaths": "শপথ",
  "Oaths (Kitab Al-Aiman)": "শপথ (কসম)",
  "Expiation for Unfulfilled Oaths": "শপথের কাফফারা",
  "Laws of Inheritance (Al-Faraa'id)": "ফারায়েয (উত্তরাধিকার)",
  "Inheritance": "মীরাস (উত্তরাধিকার)",
  "Shares of Inheritance (Kitab Al-Fara'id)": "ফারায়েয",
  "The Book of Inheritance": "মীরাস",
  "Limits and Punishments set by Allah (Hudood)": "হুদূদ (শাস্তি)",
  "Prescribed Punishments (Kitab Al-Hudud)": "হুদূদ",
  "The Book of Legal Punishments": "হুদূদ (শাস্তি)",
  "Blood Money (Ad-Diyat)": "দিয়াত (রক্তমূল্য)",
  "Dealing with Apostates": "মুরতাদদের বিধান",
  "Saying Something under Compulsion (Ikraah)": "ইকরাহ (জবরদস্তি)",
  "Tricks": "কৌশল (হীলা)",
  "Interpretation of Dreams": "স্বপ্নের ব্যাখ্যা",
  "The Book of Dream Interpretation": "স্বপ্নের ব্যাখ্যা",
  "Afflictions and the End of the World": "ফিতনা ও কিয়ামতের আলামত",
  "Afflictions": "ফিতনা",
  "Judgments (Ahkaam)": "আহকাম (বিচারকার্য)",
  "Judgments": "বিচারকার্য",
  "Judgment (Kitab Al-Aqdiyah)": "বিচারকার্য",
  "The Book of Judicial Decisions": "বিচারকার্য",
  "Wishes": "আকাঙ্ক্ষা",
  "Accepting Information Given by a Truthful Person": "সত্যবাদীর সংবাদ",
  "Holding Fast to the Quran and Sunnah": "কুরআন ও সুন্নাহ আঁকড়ে ধরা",
  "ONENESS, UNIQUENESS OF ALLAH (TAWHEED)": "তাওহীদ (একত্ববাদ)",
  "Tawheed": "তাওহীদ",
  
  // Muslim specific
  "The Book of Faith": "ঈমান",
  "The Book of Faith (Kitab Al-Iman)": "ঈমান",
  "The Book of Purification (Kitab Al-Taharah)": "পবিত্রতা (তাহারাত)",
  "The Book of Mosques and Places of Prayer": "মসজিদ ও নামাযের স্থান",
  "The Book of Prayer - Travellers": "মুসাফিরের সালাত",
  "The Book of Zakat (Kitab Al-Zakat)": "যাকাত",
  "The Book of Fasting (Kitab Al-Sawm)": "সিয়াম (রোযা)",
  "The Book of Pilgrimage (Kitab Al-Hajj)": "হজ্জ",
  "The Book of Musaqah": "মুসাকাত (চাষাবাদের চুক্তি)",
  "The Book of (Kitab Al-Musaqah)": "মুসাকাত",
  "The Book of Oaths (Kitab Al-Aiman)": "শপথ",
  "The Book of Jihad and Expedition": "জিহাদ ও অভিযান",
  "The Book of Government (Kitab Al-Imarah)": "নেতৃত্ব ও সরকার",
  "The Book of Hunting, Slaughter, and what may be Eaten": "শিকার ও যবেহ",
  "The Book of Sacrifices (Kitab Al-Adahi)": "কুরবানী",
  "The Book of Judicial Decisions (Kitab Al-Aqdiyah)": "বিচারকার্য",
  "The Book of the Merits of the Companions": "সাহাবীদের মর্যাদা",
  "The Book of Virtue, Enjoining Good Manners, and Joining of the Ties of Kinship": "সৎকর্ম ও আত্মীয়তার বন্ধন",
  "The Book of Miscellaneous ahadith of Significant Values": "বিভিন্ন গুরুত্বপূর্ণ হাদিস",
  "The Book of Commentary on the Quran": "তাফসীর",
  "The Book of Remembrance of Allah, Supplication, Repentance and Seeking Forgiveness": "যিকির, দোয়া ও তাওবা",
  "The Book of Repentance": "তাওবা",
  "The Book of Characteristics of the Hypocrites": "মুনাফিকদের বৈশিষ্ট্য",
  "The Book of Paradise, its Description, its Bounties and its Inhabitants": "জান্নাতের বিবরণ",
  "The Book of Tribulations and Portents of the Last Hour": "ফিতনা ও কিয়ামতের আলামত",
  "The Book of Zuhd and Softening of Hearts": "যুহদ ও রিকাক",
  
  // Abu Dawud specific
  "General Behavior (Kitab Al-Adab)": "আদব (শিষ্টাচার)",
  "Combing the Hair (Kitab Al-Tarajjul)": "চুল আঁচড়ানো",
  "Signet-Rings (Kitab Al-Khatam)": "আংটি",
  "Trials and Fierce Battles (Kitab Al-Fitan)": "ফিতনা ও মহাযুদ্ধ",
  "The Promised Deliverer (Kitab Al-Mahdi)": "মাহদী",
  "Battles (Kitab Al-Malahim)": "মহাযুদ্ধ",
  "Model Behavior of the Prophet (Kitab Al-Sunnah)": "সুন্নাহ",
  "Tax (Kitab Al-Kharaj, Wal-Fai' Wal-Imarah)": "কর ও খারাজ",
  "Tribute, Spoils, and Rulership (Kitab Al-Kharaj wal-Imara wal-Fai')": "খারাজ, গণীমত ও নেতৃত্ব",
  "Dialects and Readings of the Quran (Kitab Al-Huruf Wa Al-Qira'at)": "কুরআনের কিরাআত",
  "Hot Baths (Kitab Al-Hammam)": "হাম্মাম (গোসলখানা)",
  "Types of Blood-Wit (Kitab Al-Diyat)": "দিয়াত (রক্তমূল্য)",
  
  // Tirmidhi specific
  "Chapters On Taharah": "তাহারাত (পবিত্রতা)",
  "Chapters on Salat": "সালাত",
  "Chapters on Witr": "বিতর",
  "Chapters on Jumu'ah": "জুমু'আ",
  "Chapters on the Two Eids": "দুই ঈদ",
  "Chapters on Travel": "সফর",
  "Chapters On Zakat": "যাকাত",
  "Chapters on Fasting": "সিয়াম (রোযা)",
  "Chapters on Hajj": "হজ্জ",
  "Chapters on Jana'iz": "জানাযা",
  "Chapters on Marriage": "বিবাহ",
  "Chapters on Suckling": "রাদা'আ (দুগ্ধপান)",
  "Chapters on Divorce and Li'an": "তালাক ও লি'আন",
  "Chapters on Business": "ব্যবসা",
  "Chapters on Judgements": "বিচারকার্য",
  "Chapters on Blood Money": "দিয়াত",
  "Chapters on Legal Punishments": "হুদূদ (শাস্তি)",
  "Chapters on Hunting": "শিকার",
  "Chapters on Sacrifices": "কুরবানী",
  "Chapters on Vowing": "মানত",
  "Chapters on Military Expeditions": "যুদ্ধাভিযান",
  "Chapters on Jihad": "জিহাদ",
  "Chapters on Clothing": "পোশাক",
  "Chapters on Food": "খাদ্য",
  "Chapters on Drinks": "পানীয়",
  "Chapters on Righteousness And Maintaining Good Relations With Relatives": "সৎকর্ম ও আত্মীয়তা",
  "Chapters on Medicine": "চিকিৎসা",
  "Chapters on Inheritance": "মীরাস",
  "Chapters on Al-Fitan": "ফিতনা",
  "Chapters on Dreams": "স্বপ্ন",
  "Chapters on Virtues": "ফযীলত",
  "Chapters on Manners": "আদব",
  "Chapters on Parables": "দৃষ্টান্ত",
  "Chapters on the description of the Day of Judgement, Ar-Riqaq, and Al-Wara'": "কিয়ামত ও রিকাক",
  "Chapters On Zuhd": "যুহদ (দুনিয়া বিমুখতা)",
  "Chapters on the description of Paradise": "জান্নাতের বিবরণ",
  "Chapters on the description of Hellfire": "জাহান্নামের বিবরণ",
  "Chapters On Faith": "ঈমান",
  "Chapters On Knowledge": "ইলম (জ্ঞান)",
  "Chapters On Seeking Permission": "অনুমতি চাওয়া",
  "Chapters On Etiquette": "আদব",
  "Chapters on Letter of the Prophet ﷺ to different Countries": "নবী (ﷺ)-এর চিঠিপত্র",
  "Chapters on Supplications": "দোয়া",
  "Chapters on Tafsir": "তাফসীর",
  "Chapters on Recitation": "কিরাআত",
  "Chapters on Virtues of the Quran": "কুরআনের ফযীলত",
  "Chapters on Da'awat": "দোয়া",
  
  // Nasai specific
  "The Book of Water": "পানি",
  "The Book of Menstruation and Istihadah": "হায়েয ও ইস্তিহাযা",
  "The Book of Ghusl and Tayammum": "গোসল ও তায়াম্মুম",
  "The Book of Salah": "সালাত",
  "The Book of the Times (of Prayer)": "সালাতের ওয়াক্ত",
  "The Book of the Adhan (The Call to Prayer)": "আযান",
  "The Book of the Masjids": "মসজিদসমূহ",
  "The Book of the Qiblah": "কিবলা",
  "The Book of Leading the Prayer (Imamah)": "ইমামত",
  "The Book of the Commencement of the Prayer": "সালাত শুরু করা",
  "The Book of the At-Tatbiq (Clasping One's Hands Together)": "তাতবীক",
  "The Book of Forgetfulness (In Prayer)": "সাহু সিজদা",
  "The Book of Jumu'ah (Friday Prayer)": "জুমু'আ",
  "The Book of Shortening the Prayer When Traveling": "সফরে সালাত কসর",
  "The Book of the Fear Prayer": "সালাতুল খাওফ",
  "The Book of the Prayer for the Two Eids": "ঈদের সালাত",
  "The Book of Qiyam Al-Lail (The Night Prayer) and Voluntary Prayers During the Day": "তাহাজ্জুদ ও নফল",
  "The Book of Prostration of Forgetfulness": "সাহু সিজদা",
  "The Book of the Conditions of Salah": "সালাতের শর্তাবলী",
  "The Book of the Isha Prayer": "ইশার সালাত",
  
  // Ibn Majah specific
  "The Book of the Sunnah": "সুন্নাহ",
  "The Book of Purification and its Sunnah": "পবিত্রতা ও সুন্নাহ",
  "The Book of the Adhan and the Sunnah Regarding It": "আযান ও এর সুন্নাহ",
  "Establishing the Prayer and the Sunnah Regarding Them": "সালাত প্রতিষ্ঠা ও সুন্নাহ",
  "The Chapters on the Mosques and the Congregations": "মসজিদ ও জামাআত",
  "The Book of Establishing the Prayer and the Sunnah Regarding Them": "সালাত প্রতিষ্ঠা",
  "Chapters on Funerals": "জানাযা",
  "Chapters on Zakat": "যাকাত",
  "Chapters on Fasting (Ibn Majah)": "সিয়াম",
  "Chapters on Hajj Rituals": "হজ্জের মানাসিক",
  "The Chapters on Marriage": "বিবাহ",
  "The Chapters on Divorce": "তালাক",
  "The Chapters on Expiation": "কাফফারা",
  "The Chapters on Business Transactions": "ব্যবসায়িক লেনদেন",
  "The Chapters on Rulings": "আহকাম (বিধান)",
  "The Chapters on Gifts": "হিবা (উপহার)",
  "The Chapters on Charity": "সাদাকা",
  "The Chapters on Pawning": "বন্ধক",
  "The Chapters on Pre-emption": "শুফ'আ",
  "The Chapters on Lost Property": "লুকাতা",
  "The Chapters on Freeing Slaves": "দাস মুক্তি",
  "The Chapters on Legal Punishments": "হুদূদ",
  "The Chapters on Blood Money": "দিয়াত",
  "The Chapters on Wills": "ওসিয়ত",
  "Chapters on Jihad (Ibn Majah)": "জিহাদ",
  "The Chapters on Dress": "পোশাক",
  "The Chapters on Adab": "আদব",
  "The Chapters on Supplication": "দোয়া",
  "The Chapters on Interpretation of Dreams": "স্বপ্নের ব্যাখ্যা",
  "The Chapters on Tribulations": "ফিতনা",
  "The Chapters on Asceticism": "যুহদ",
  "The Chapters on Medicine": "চিকিৎসা",
  "The Chapters on Etiquette": "আদব ও শিষ্টাচার",
  "The Chapters on Food": "খাদ্য",
  "The Chapters on Drinks": "পানীয়",
  "The Chapters on Slaughtering": "যবেহ",
  "The Chapters on Hunting": "শিকার",
  
  // Generic terms
  "Tafsir": "তাফসীর",
  "Virtues": "ফযীলত",
  "Manners": "আদব",
  "Paradise": "জান্নাত",
  "Hellfire": "জাহান্নাম",
  "Repentance": "তাওবা",
  "Asceticism": "যুহদ",
  "Charity": "সাদাকা",
  "Supplication": "দোয়া",
  "Etiquette": "আদব ও শিষ্টাচার",
  "Tribulations": "ফিতনা",
  "Zuhd": "যুহদ (দুনিয়া বিমুখতা)",

  // Bukhari missing
  "Prostration During Recital of Qur'an": "সিজদাতুত তিলাওয়াত",
  "Transferance of a Debt from One Person to Another (Al-Hawaala)": "হাওয়ালা",
  "Kafalah": "কাফালা (জামানত)",
  "Khusoomaat": "বিবাদ-মোকাদ্দমা",
  "Lost Things Picked up by Someone (Luqatah)": "লুকাতা (কুড়িয়ে পাওয়া বস্তু)",
  "Makaatib": "মুকাতাব (চুক্তিবদ্ধ দাস মুক্তি)",
  "Jizyah and Mawaada'ah": "জিযিয়া ও সন্ধি",
  "Military Expeditions led by the Prophet (pbuh) (Al-Maghaazi)": "মাগাযী (যুদ্ধাভিযান)",
  "Prophetic Commentary on the Qur'an (Tafseer of the Prophet (pbuh))": "তাফসীর (নবীর ব্যাখ্যা)",
  "Hunting, Slaughtering": "শিকার ও যবেহ",
  "(Statements made under) Coercion": "ইকরাহ (জবরদস্তি)",
  "Virtues and Merits of the Prophet (pbuh) and his Companions": "নবী ও সাহাবীদের মর্যাদা",
  "Apostates": "মুরতাদদের বিধান",
  "Oneness, Uniqueness of Allah (Tawheed)": "তাওহীদ (একত্ববাদ)",
  "Virtues of the Night of Qadr": "লাইলাতুল কদরের ফযীলত",
  "Shuf'a": "শুফ'আ (অগ্রক্রয়)",
  "Forgetfulness in Prayer": "সালাতে ভুল (সাহু)",
  "Virtues of Prayer at Masjid Makkah and Madinah": "মক্কা ও মদীনার মসজিদে সালাতের ফযীলত",
  "`Umrah (Minor pilgrimage)": "উমরা",

  // Muslim missing
  "The Book of Suckling": "দুগ্ধপান (রাদা'আ)",
  "The Book of Invoking Curses": "লি'আন (অভিশাপ)",
  "The Book of Emancipating Slaves": "দাস মুক্তি (ইতক)",
  "The Book of Transactions": "লেনদেন (মুআমালাত)",
  "The Book of Vows": "মানত (নযর)",
  "The Book of Lost Property": "লুকাতা (হারানো বস্তু)",
  "The Book on Government": "নেতৃত্ব ও সরকার (ইমারাত)",
  "The Book of Greetings": "সালাম (অভিবাদন)",
  "The Book Concerning the Use of Correct Words": "শব্দ প্রয়োগের শিষ্টাচার",
  "The Book of Poetry": "কবিতা",
  "The Book of Dreams": "স্বপ্ন",
  "The Book of Heart-Melting Traditions": "রিকাক (হৃদয়গ্রাহী হাদিস)",
  "Characteristics of The Hypocrites And Rulings Concerning Them": "মুনাফিকদের বৈশিষ্ট্য ও বিধান",
  "The Book of Commentary on the Qur'an": "তাফসীর",
  "The Book of Menstruation": "হায়েয (ঋতুস্রাব)",
  "The Book of Prayers ": "সালাত (নামায)",
  "The Book of Prayer - Friday": "জুমু'আর সালাত",
  "The Book of Prayer - Two Eids": "দুই ঈদের সালাত",
  "The Book of Prayer - Rain": "বৃষ্টির জন্য সালাত (ইসতিসকা)",
  "The Book of Prayer - Eclipses": "গ্রহণের সালাত",
  "The Book of Prayer - Funerals": "জানাযার সালাত",
  "The Book of Fasting ": "সিয়াম (রোযা)",
  "The Book of I'tikaf": "ই'তিকাফ",
  "The Book of Pilgrimage": "হজ্জ",
  "The Book of the Rules of Inheritance": "মীরাসের বিধান",
  "The Book of Oaths, Muharibin, Qasas (Retaliation), and Diyat (Blood Money)": "শপথ, কিসাস ও দিয়াত",
  "The Book of Divorce ": "তালাক",
  "The Book of Virtues": "ফযীলত",
  "The Book of Knowledge": "ইলম (জ্ঞান)",
  "The Book Pertaining to the Remembrance of Allah, Supplication, Repentance and Seeking Forgiveness ": "যিকির, দোয়া, তাওবা ও ইসতিগফার",
  "Characteristics of the Day of Judgment, Paradise, and Hell": "কিয়ামত, জান্নাত ও জাহান্নামের বিবরণ",
  "The Book of Zuhd and Softening of Hearts ": "যুহদ ও রিকাক",

  // Abu Dawud missing
  "The Book of Lost and Found Items": "লুকাতা (হারানো ও প্রাপ্ত বস্তু)",
  "Game (Kitab Al-Said)": "শিকার (কিতাবুস সাইদ)",
  "Tribute, Spoils, and Rulership (Kitab Al-Kharaj, Wal-Fai' Wal-Imarah)": "খারাজ, ফাই ও ইমারাত",
  "Wages (Kitab Al-Ijarah)": "ইজারা (ভাড়া ও মজুরি)",
  "The Office of the Judge (Kitab Al-Aqdiyah)": "বিচারকার্য (কাযা)",
  "Divination and Omens (Kitab Al-Kahanah Wa Al-Tatayyur)": "ভাগ্যগণনা ও কুলক্ষণ",
  "Trials and Fierce Battles (Kitab Al-Fitan Wa Al-Malahim)": "ফিতনা ও মহাযুদ্ধ",
  "The Book Of The Prayer For Rain (Kitab al-Istisqa')": "ইসতিসকা (বৃষ্টির দোয়া)",
  "Prayer (Kitab Al-Salat): Detailed Rules of Law about the Prayer during Journey": "সফরের সালাতের বিধান",
  "Prayer (Kitab Al-Salat): Detailed Injunctions about Ramadan": "রামাদানের বিশেষ বিধান",
  "Prayer (Kitab Al-Salat): Prostration while reciting the Qur'an": "তিলাওয়াতের সিজদা",
  "Prayer (Kitab Al-Salat): Detailed Injunctions about Witr": "বিতর সালাতের বিধান",
  "The Rites of Hajj (Kitab Al-Manasik Wa'l-Hajj)": "হজ্জ (মানাসিক)",
  "Oaths and Vows (Kitab Al-Aiman Wa Al-Nudhur)": "শপথ ও মানত",

  // Tirmidhi missing
  "The Book on Purification": "তাহারাত (পবিত্রতা)",
  "The Book on Salat (Prayer)": "সালাত (নামায)",
  "The Book on Al-Witr": "বিতর সালাত",
  "The Book on the Day of Friday": "জুমু'আ",
  "The Book on the Two Eids": "দুই ঈদ",
  "The Book on Traveling": "সফর",
  "The Book on Zakat": "যাকাত",
  "The Book on Fasting": "সিয়াম (রোযা)",
  "The Book on Hajj": "হজ্জ",
  "The Book on Jana''iz (Funerals)": "জানাযা",
  "The Book on Marriage": "বিবাহ (নিকাহ)",
  "The Book on Suckling": "রাদা'আ (দুগ্ধপান)",
  "The Book on Divorce and Li'an": "তালাক ও লি'আন",
  "The Book on Business": "ব্যবসা-বাণিজ্য",
  "The Chapters On Judgements From The Messenger of Allah": "রাসূলুল্লাহ (ﷺ)-এর বিচারকার্য",
  "The Book on Blood Money": "দিয়াত (রক্তমূল্য)",
  "The Book on Legal Punishments (Al-Hudud)": "হুদূদ (শাস্তি)",
  "The Book on Hunting": "শিকার",
  "The Book on Sacrifices": "কুরবানী",
  "The Book on Vows and Oaths": "মানত ও শপথ",
  "The Book on Military Expeditions": "যুদ্ধাভিযান",
  "The Book on Clothing": "পোশাক",
  "The Book on Food": "খাদ্য",
  "The Book on Drinks": "পানীয়",
  "Chapters On Wasaya (Wills and Testament)": "ওসিয়ত",
  "Chapters On Wala' And Gifts": "ওয়ালা ও হিবা",
  "Chapters On Al-Qadar": "তাকদীর (আল-কাদার)",
  "Chapters On Witnesses": "সাক্ষ্য",
  "The Book on the Description of Hellfire": "জাহান্নামের বিবরণ",
  "The Book on Faith": "ঈমান",
  "Chapters on The Virtues of the Qur'an": "কুরআনের ফযীলত",
  "The Book on Virtues of Jihad": "জিহাদের ফযীলত",
  "The Book on Jihad": "জিহাদ",

  // Nasai missing
  "The Book of Praying for Rain (Al-Istisqa')": "ইসতিসকা (বৃষ্টির দোয়া)",
  "The Book of the Prayer for the Two 'Eids": "দুই ঈদের সালাত",
  "The Book of Zakah": "যাকাত",
  "The Book of Horses, Races and Shooting": "ঘোড়া, প্রতিযোগিতা ও তীরন্দাজি",
  "The Book of Endowments": "ওয়াকফ (এনডাওমেন্ট)",
  "The Book of Presents": "উপহার (হিবা)",
  "The Book of ar-Ruqba": "রুকবা (শর্তসাপেক্ষ দান)",
  "The Book of 'Umra": "উমরা",
  "The Book of the Kind Treatment of Women": "নারীদের প্রতি সদ্ব্যবহার",
  "The Book of Fighting [The Prohibition of Bloodshed]": "রক্তপাত নিষেধ ও যুদ্ধ",
  "The Book of Distribution of Al-Fay'": "ফাই বন্টন",
  "The Book of al-Bay'ah": "বাই'আত (আনুগত্যের শপথ)",
  "The Book of al-'Aqiqah": "আকীকা",
  "The Book of al-Fara' and al-'Atirah": "ফারা ও আতীরা",
  "The Book of Hunting and Slaughtering": "শিকার ও যবেহ",
  "The Book of ad-Dahaya (Sacrifices)": "কুরবানী (দাহায়া)",
  "The Book of Financial Transactions": "আর্থিক লেনদেন",
  "The Book of Oaths (qasamah), Retaliation and Blood Money": "কাসামা, কিসাস ও দিয়াত",
  "The Book of Cutting off the Hand of the Thief": "চোরের হাত কাটা",
  "The Book Of Faith and its Signs": "ঈমান ও এর আলামত",
  "The Book of Adornment": "সাজসজ্জা",
  "The Book of the Etiquette of Judges": "বিচারকদের আদব",
  "The Book of Seeking Refuge with Allah": "আল্লাহর কাছে আশ্রয় প্রার্থনা",
  "The Book of Leading the Prayer (Al-Imamah)": "ইমামত (নামাযে নেতৃত্ব)",
  "The Book of The At-Tatbiq (Clasping One's Hands Together)": "তাতবীক (হাত বাঁধা)",

  // Ibn Majah missing
  "The Book On The Mosques And The Congregations": "মসজিদ ও জামাআত",
  "Chapters Regarding Funerals": "জানাযা",
  "The Chapters Regarding Zakat": "যাকাত",
  "The Chapters on Manumission (of Slaves)": "দাস মুক্তি",
  "Chapters on Shares of Inheritance": "মীরাসের অংশ",
  " Chapters on Food": "খাদ্য",
  "The Book of the Prayer": "সালাত (নামায)",
};

/**
 * Translate an English hadith section name to Bengali.
 * Tries exact match first, then partial match.
 */
export const translateSectionName = (englishName: string): string => {
  if (!englishName) return "";
  
  // Exact match
  if (SECTION_NAME_MAP[englishName]) return SECTION_NAME_MAP[englishName];
  
  // Case-insensitive exact match
  const lowerName = englishName.toLowerCase().trim();
  for (const [key, val] of Object.entries(SECTION_NAME_MAP)) {
    if (key.toLowerCase() === lowerName) return val;
  }
  
  // Partial match - check if any key is contained in the name
  for (const [key, val] of Object.entries(SECTION_NAME_MAP)) {
    if (englishName.includes(key) || key.includes(englishName)) return val;
  }
  
  // Return original if no match found
  return englishName;
};
