project_id = "laasotunayiivssffhnu"

[functions.send-email]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.send-push]
verify_jwt = false