import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import AdminPageWrapper from "@/components/admin/AdminPageWrapper";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { toast } from "sonner";
import { Plus, Trash2, Search, Award } from "lucide-react";
import { useSectionPermissions } from "@/hooks/useSectionPermissions";

const AdminCertificates = () => {
  const queryClient = useQueryClient();
  const { canEdit, canDelete } = useSectionPermissions();
  const [search, setSearch] = useState("");
  const [showDialog, setShowDialog] = useState(false);
  const [selectedStudentId, setSelectedStudentId] = useState("");
  const [selectedExamId, setSelectedExamId] = useState("");

  const { data: certificates, isLoading } = useQuery({
    queryKey: ["admin_certificates"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("certificates")
        .select("*, students(name, roll_number, class_name), exams(name, year)")
        .order("created_at", { ascending: false });
      if (error) throw error;
      return data;
    },
  });

  const { data: students } = useQuery({
    queryKey: ["admin_students_for_cert"],
    queryFn: async () => {
      const { data, error } = await supabase.from("students").select("id, name, roll_number, class_name").eq("is_active", true).order("name");
      if (error) throw error;
      return data;
    },
  });

  const { data: exams } = useQuery({
    queryKey: ["admin_exams_for_cert"],
    queryFn: async () => {
      const { data, error } = await supabase.from("exams").select("id, name, year").order("year", { ascending: false });
      if (error) throw error;
      return data;
    },
  });

  const createMutation = useMutation({
    mutationFn: async () => {
      const { error } = await supabase.from("certificates").insert({
        student_id: selectedStudentId,
        exam_id: selectedExamId,
        certificate_number: "", // auto-generated by trigger
        verification_code: "", // auto-generated by trigger
      });
      if (error) throw error;
    },
    onSuccess: () => {
      toast.success("সনদপত্র তৈরি হয়েছে!");
      queryClient.invalidateQueries({ queryKey: ["admin_certificates"] });
      setShowDialog(false);
      setSelectedStudentId("");
      setSelectedExamId("");
    },
    onError: (e: any) => toast.error(e.message),
  });

  const deleteMutation = useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase.from("certificates").delete().eq("id", id);
      if (error) throw error;
    },
    onSuccess: () => {
      toast.success("মুছে ফেলা হয়েছে!");
      queryClient.invalidateQueries({ queryKey: ["admin_certificates"] });
    },
  });

  const filtered = certificates?.filter((c: any) =>
    !search || c.students?.name?.toLowerCase().includes(search.toLowerCase()) ||
    c.certificate_number?.toLowerCase().includes(search.toLowerCase()) ||
    c.verification_code?.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <AdminPageWrapper title="সনদপত্র ব্যবস্থাপনা" icon={Award}>
      <div className="flex flex-col sm:flex-row gap-3 mb-4">
        <div className="relative flex-1">
          <Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" />
          <Input placeholder="সনদ নম্বর, নাম বা কোড খুঁজুন..." value={search} onChange={(e) => setSearch(e.target.value)} className="pl-9" />
        </div>
        {canEdit && (
          <Dialog open={showDialog} onOpenChange={setShowDialog}>
            <DialogTrigger asChild>
              <Button className="gap-1.5"><Plus size={16} /> নতুন সনদ</Button>
            </DialogTrigger>
            <DialogContent>
              <DialogHeader><DialogTitle>নতুন সনদপত্র তৈরি</DialogTitle></DialogHeader>
              <div className="space-y-4 pt-2">
                <div>
                  <label className="text-sm font-medium mb-1.5 block">শিক্ষার্থী</label>
                  <Select value={selectedStudentId} onValueChange={setSelectedStudentId}>
                    <SelectTrigger><SelectValue placeholder="শিক্ষার্থী নির্বাচন করুন" /></SelectTrigger>
                    <SelectContent>
                      {students?.map((s) => (
                        <SelectItem key={s.id} value={s.id}>{s.name} — রোল: {s.roll_number} ({s.class_name})</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <div>
                  <label className="text-sm font-medium mb-1.5 block">পরীক্ষা</label>
                  <Select value={selectedExamId} onValueChange={setSelectedExamId}>
                    <SelectTrigger><SelectValue placeholder="পরীক্ষা নির্বাচন করুন" /></SelectTrigger>
                    <SelectContent>
                      {exams?.map((e) => (
                        <SelectItem key={e.id} value={e.id}>{e.name} ({e.year})</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <Button onClick={() => createMutation.mutate()} disabled={!selectedStudentId || !selectedExamId || createMutation.isPending} className="w-full">
                  সনদ তৈরি করুন
                </Button>
              </div>
            </DialogContent>
          </Dialog>
        )}
      </div>

      <div className="border rounded-lg overflow-auto">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>শিক্ষার্থী</TableHead>
              <TableHead>শ্রেণি</TableHead>
              <TableHead>পরীক্ষা</TableHead>
              <TableHead>সনদ নম্বর</TableHead>
              <TableHead>যাচাই কোড</TableHead>
              <TableHead>স্ট্যাটাস</TableHead>
              {canDelete && <TableHead className="w-12"></TableHead>}
            </TableRow>
          </TableHeader>
          <TableBody>
            {isLoading ? (
              <TableRow><TableCell colSpan={7} className="text-center py-8">লোড হচ্ছে...</TableCell></TableRow>
            ) : !filtered?.length ? (
              <TableRow><TableCell colSpan={7} className="text-center py-8 text-muted-foreground">কোনো সনদ নেই</TableCell></TableRow>
            ) : (
              filtered.map((c: any) => (
                <TableRow key={c.id}>
                  <TableCell className="font-medium">{c.students?.name || "—"}</TableCell>
                  <TableCell>{c.students?.class_name || "—"}</TableCell>
                  <TableCell>{c.exams?.name} ({c.exams?.year})</TableCell>
                  <TableCell><code className="text-xs">{c.certificate_number}</code></TableCell>
                  <TableCell><code className="text-xs">{c.verification_code}</code></TableCell>
                  <TableCell>
                    <Badge variant={c.status === "active" ? "default" : "secondary"}>
                      {c.status === "active" ? "সক্রিয়" : "বাতিল"}
                    </Badge>
                  </TableCell>
                  {canDelete && (
                    <TableCell>
                      <Button variant="ghost" size="icon" onClick={() => deleteMutation.mutate(c.id)}>
                        <Trash2 size={14} className="text-destructive" />
                      </Button>
                    </TableCell>
                  )}
                </TableRow>
              ))
            )}
          </TableBody>
        </Table>
      </div>
    </AdminPageWrapper>
  );
};

export default AdminCertificates;
